// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjXcsgz-wdHa__F4sGkvSnuu_Qo5QTFI',
    appId: '1:776044253883:android:71e636f24a12238bcbcf9e',
    messagingSenderId: '776044253883',
    projectId: 'doormartdelivery-d7adf',
    storageBucket: 'doormartdelivery-d7adf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvDJmDkJ0V03SdQ1tH7GY3soJTqlmJG8',
    appId: '1:39851747839:ios:402545516d1f3f6edadfca',
    messagingSenderId: '39851747839',
    projectId: 'doormart-delivery',
    storageBucket: 'doormart-delivery.firebasestorage.app',
    iosBundleId: 'com.example.doormartdelivery',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_TfN2Ym6KH98H4WTiThENmArNGAF59Ho',
    appId: '1:39851747839:web:736948c25db6a1eddadfca',
    messagingSenderId: '39851747839',
    projectId: 'doormart-delivery',
    authDomain: 'doormart-delivery.firebaseapp.com',
    storageBucket: 'doormart-delivery.firebasestorage.app',
  );
}
